export const environment = {
  SELF_DESCRIPTION_URL: 'https://localhost:8444/',
  PROXY_ENDPOINT_URL: 'https://localhost:8183/proxy',
  SELF_DESCRIPTION_API: 'api/selfDescription/',
  CONTRACT_OFFER_API: 'api/contractOffer/',
  OFFERED_RESOURCE_API: 'api/offeredResource/',
  REPRESENTATION_API: 'api/representation/',
  MULTIPART_TYPE: 'form',
  FORWARD_TO: 'https://localhost:8889/data',
  TC_AES_SECRET_KEY: '1312312312',
  TC_BROKER_URL: 'https://broker.ids.isst.fraunhofer.de/infrastructure',
  TC_ECC_KEYSTORE_NAME: 'true-connector-provider-keystore.jks',
  TC_ECC_KEY_PASSWORD: 'changeit',
  TC_ECC_KEYSTORE_PASSWORD: 'changeit',
  TC_ECC_ALIAS: 'true-connector-provider',
  TC_ECC_TRUSTORE_NAME: 'true-connector-provider-truststore.jks',
  TC_ECC_TRUSTORE_PASSWORD: 'providerTruststore',
  TC_DA_KEYSTORE_NAME: 'true-connector-provider-keystore.jks',
  TC_DA_KEY_PASSWORD: 'changeit',
  TC_DA_KEYSTORE_PASSWORD: 'changeit',
  TC_DA_ALIAS: 'true-connector-provider',
  TC_DA_TRUSTORE_NAME: 'true-connector-provider-truststore.jks',
  TC_DA_TRUSTORE_PASSWORD: 'providerTruststore',
  TC_CACHE_TOKEN: 'false',
  TC_FETCH_TOKEN_ON_STARTUP: 'false',
  TC_MULTIPART_ECC: 'form',
  TC_WS_ECC: 'false',
  TC_IDSCP2: 'false',
  TC_EXTRACT_PAYLOAD_FROM_RESPONSE: 'true',
  TC_VALIDATE_SELF_DESCRIPTION: 'false',
  TC_MULTIPART_EDGE: 'form',
  TC_ISSUER_CONNECTOR_URI: 'http://w3id.org/engrd/connector/provider',
  TC_ECC_FIREWALL: 'true',
  TC_DA_FIREWALL: 'true',
  TC_DATA_APP_ENDPOINT: 'https://be-dataapp-consumer:8083/data',
  TC_WS_EDGE: 'false',
  TC_CONNECTOR_ID: 'http://w3id.org/engrd/connector/consumer',
  TC_UC_DATAAPP_URI:
    'https://uc-dataapp-consumer:8080/platoontec/PlatoonDataUsage/1.0/',
  TC_DAPS_KEYSTORE_NAME: 'daps-keystore.jks',
  TC_DAPS_KEYSTORE_PASSWORD: 'changeit',
  TC_DAPS_KEYSTORE_ALIAS: 'daps',
};
