name: Main release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version (e.g., 1.0.0)"
        required: true
      developmentVersion:
        description: "Next development version (e.g., 1.1.0)"
        required: true

jobs:
  main_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Application
        run: npm run build

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"

      - name: Check and Update to Release Version
        id: update_release_version
        run: |
          npm version ${{ github.event.inputs.releaseVersion }} --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "[release] Update to version ${{ github.event.inputs.releaseVersion }}"
          git push origin main

      - name: Create and Push Release Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a ${{ github.event.inputs.releaseVersion }} -m "Release version ${{ github.event.inputs.releaseVersion }}"
          git push origin ${{ github.event.inputs.releaseVersion }}

      - name: Bump Development Version
        run: |
          npm version ${{ github.event.inputs.developmentVersion }} --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "[release] Bump to next development version ${{ github.event.inputs.developmentVersion }}"
          git push origin main

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Extract Release Notes
        id: extract_notes
        run: |
          RELEASE_VERSION=${{ github.event.inputs.releaseVersion }}
          NOTES=$(awk '/## \['"$RELEASE_VERSION"'\]/{flag=1;next}/^## \[/{flag=0}flag' CHANGELOG.md)
          if [ -z "$NOTES" ]; then
            NOTES="No release notes found for version $RELEASE_VERSION"
          fi
          echo "${NOTES}" > release_notes.md
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat release_notes.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get Previous Tag
        id: prev_tag
        run: |
          TAG_COUNT=$(git tag | wc -l)
          if [ "$TAG_COUNT" -lt 2 ]; then
            PREVIOUS_TAG="none"
          else
            PREVIOUS_TAG=$(git tag --sort=-creatordate | head -n 2 | tail -n 1)
          fi
          echo "previous_tag=${PREVIOUS_TAG}" >> $GITHUB_OUTPUT

      - name: Create Full Changelog URL
        id: changelog_url
        run: |
          REPO_URL="https://github.com/Engineering-Research-and-Development/true-connector-ui"
          CURRENT_TAG=${{ github.event.inputs.releaseVersion }}
          PREVIOUS_TAG=${{ steps.prev_tag.outputs.previous_tag }}
          CHANGELOG_URL="${REPO_URL}/compare/${PREVIOUS_TAG}...${CURRENT_TAG}"
          echo "url=${CHANGELOG_URL}" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FULL_NOTES="${{ steps.extract_notes.outputs.notes }}\n\n**Full Changelog**: ${{ steps.changelog_url.outputs.url }}"
          echo "${FULL_NOTES}"
          gh release create ${{ github.event.inputs.releaseVersion }} --title "${{ github.event.inputs.releaseVersion }}" --notes "${FULL_NOTES}"

      - name: Create A Pull Request
        uses: thomaseizinger/create-pull-request@1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: main
          base: develop
          title: Released main into develop
          body: |
            Hi!
            This PR was created in response to a workflow run.
            I've updated the version name and code commit.
