name: Build TRUE Connector UI and run GH Action

on:
  push:
    branches: ["feature/*", "hotfix/*", "develop", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    steps:
      - uses: actions/checkout@v4

      - name: Run Creating Docker Image from DataApp repo
        run: ./ci/deploy.sh
